### ISSUE TITLE
GUI does not react

### ISSUE THREAD

**Issue by zettberlin** [DenisSalem/DStudio#2]
Built today on Ubuntu Studio.
No Warnings or anything..
The application shows up as audio source in jack after loading a sample. Yet no MIDI.
The GUI does not show any graphs(wheels and fader animation does work)
The buttons lower mid do not react(neither push animation nor function) sole exception is the load sample button.

**Comment by DenisSalem** [comment]
Still a wip, not every UI widget are implemented.
